### DISCUSSION TITLE
Where is the code that hides url links in source mode?

### DISCUSSION THREAD

**Discussion by fi5sh** [chrisgrieser/shimmering-focus#218] [Q&A] [answered]
I like how this theme hides url links but I can't find what part of the code does this.

I've searched this repo for url, fold, collapsible, etc but no luck.

**Comment by chrisgrieser** [comment, marked as answer]
Hi, this snippet does the job. (in my theme, I use a different icon set, so I replaced that icon with a link-emoji for this snippet.)

```css
body:not(.show-urls) .cm-s-obsidian:not(.is-live-preview) .cm-line:not(.cm-active) .cm-string.cm-url:not(.cm-formatting) {
	font-size: 0;
}

body:not(.show-urls) .cm-s-obsidian:not(.is-live-preview) .cm-line:not(.cm-active) .cm-string.cm-url:not(.cm-formatting)::after {
	content: "🔗";
	position: relative;
	top: 2px;
}

.external-link {
	background-image: none;
	padding-right: 0;
}

```
