### DISCUSSION TITLE
Shimmering Focus × visua1hue

### DISCUSSION THREAD

**Discussion by visua1hue** [chrisgrieser/shimmering-focus#252] [Suggest your color scheme for inclusion in Shimmering Focus]
Current setup  💯, plus some additional snippets 

```CSS
.theme-dark.theme-dark {
	--bg-hue-dark: 235;
        --bg-sat: 20%;

	--color-accent: hsl(184, 79%, 45%);
	--color-accent-hsl: 184 79% 35%;
	--interactive-accent: hsl(184 79% 30%);

	--secondary-accent: hsl(252, 100%, 75%);
	--hover-accent: var(--color-accent);
	--link-unresolved-color: var(--text-gray);
	--link-external-color: hsl(179, 82%, 64%);
	--checkbox-radius: 5px;
	--checkbox-color: var(--color-yellow);
}
```

**Comment by jakecb123** [comment]
thanks for this, have you made any changes since?

**Comment by visua1hue** [comment]
Hello @github-jake, sorry for my late reply. I've changed quite a few things.

```css
.theme-dark.theme-dark {
    --bg-hue-dark: 235;
    --bg-sat: 12%;

    --color-base-00:  #181c20;
    --color-base-10:  #282b2d;
    --color-base-20:  #101316;
    --color-base-25:  #2c313c;
    --color-base-30:  #35393e;
    --color-base-35:  #3f3f3f;
    --bg1: var(--color-base-20);
    --bg2: var(--color-base-00);
    --bg3: var(--color-base-00);
    --bg4: var(--color-base-25);
    --bg5: var(--color-base-30);
    --bg6: var(--color-base-35);
    --titlebar-background: var(--color-base-00);
    --titlebar-background-focused: var(--color-base-00);

    --color-accent: hsl(184, 79%, 45%);
    --color-accent-hsl: 184 79% 35%;
    --interactive-accent: hsl(184 79% 30%);

    --secondary-accent: hsl(59, 64%, 66%);
    --hover-accent: var(--color-accent);
    --link-unresolved-color: var(--text-gray);
    --link-external-color: hsl(179, 82%, 64%);
    --checkbox-radius: 5px;
    --checkbox-color: var(--color-yellow);


    --background-code: hsl(232, 21%, 14%);
    --graph-node-attachment: hsl(234, 20%, 20%);
    --font-heading-theme: var(--font-canvas-cards-heading-theme);
    --header-height: 32px;
    --signature: " ";
}
```
Here are all my snippets – including the links to the gists. 

↖ [Typo.css](https://gist.github.com/visua1hue/1e8f02e4cd1b4538bdee3c54887ebe8c)
↖ [UI Elements.css](https://gist.github.com/visua1hue/60b9d7fd16f7199ceed82465e4286e88)
