### DISCUSSION TITLE
Gruvbox Light

### DISCUSSION THREAD

**Discussion by robrecord** [chrisgrieser/shimmering-focus#257] [Suggest your color scheme for inclusion in Shimmering Focus]
A work in progress

```css
.theme-light.theme-light {
	--color-red: rgb(157, 0, 6);
	--color-green: rgb(121, 116, 14);
	--color-yellow: rgb(181, 118, 20);
	--color-blue: rgb(7, 102, 120);
	--color-purple: rgb(143, 63, 113);
	--color-cyan: rgb(66, 123, 88);
	--color-orange: rgb(175, 58, 3);
	--color-red-rgb: 157, 0, 6;
	--color-green-rgb: 121, 116, 14;
	--color-yellow-rgb: 181, 118, 20;
	--color-blue-rgb: 7, 02, 120;
	--color-purple-rgb: 143, 63, 113;
	--color-cyan-rgb: 66, 123, 88;
	--color-orange-rgb: 175, 58, 3;
	--color-pink: var(--color-purple);
	--color-pink-rgb: var(--color-purple-rgb);
	--color-base-00: #fbf1c7;
	--color-base-05: #f2e5bc;
	--color-base-10: #ebdbb2;
	--color-base-20: #d5c4a1;
	--color-base-25: #c9b99a;
	--color-base-30: #bdae93;
	--color-base-35: #b2a48c;
	--color-base-40: #a89984;
	--color-base-50: #928374;
	--color-base-60: #7c6f64;
	--color-base-70: #665c54;
	--color-base-80: #504945;
	--color-base-85: #46403e;
	--color-base-90: #3c3836;
	--color-base-95: #32302f;
	--color-base-100: #282828;

	--bg-hue: 39;
	--bg-sat: 0%;

	--bg2: var(--color-base-05);
	--bg3: var(--color-base-10);
	--bg4: var(--color-base-20);
	--bg5: var(--color-base-25);
	--bg6: var(--color-base-30);
	/* red */
	--color-accent: var(--color-red);
	--color-accent-hsl: 358 100% 31%;
	/* orange */
	--interactive-accent: var(--color-orange);

	/* blue */
	--secondary-accent: var(--color-blue);
	/* orange strong */
	--hover-accent: hsl(24 88% 45%);
	/* aqua */
	--link-unresolved-color: var(--color-cyan);
}
```

**Comment by leowucn** [comment]
Expecting a corresponding dark background.

**Reply by robrecord** [reply]
Thanks for reminder; will adapt + submit when I get a chance.

**Comment by NachiketNamjoshi** [comment]
@leowucn Here is what i came up with based on this just in case anyone wants the dark version

```css
.theme-dark.theme-dark {
	--color-red: rgb(204, 36, 29);
	--color-green: rgb(152, 151, 26);
	--color-yellow: rgb(215, 153, 33);
	--color-blue: rgb(69, 133, 136);
	--color-purple: rgb(177, 98, 34);
	--color-cyan: rgb(66, 123, 88);
	--color-orange: rgb(254, 128, 25);
	--color-red-rgb: 204, 36, 29;
	--color-green-rgb: 152, 151, 26;
	--color-yellow-rgb: 215, 153, 33;
	--color-blue-rgb: 69, 133, 136;
	--color-purple-rgb: 177, 98, 34;
	--color-cyan-rgb: 66, 123, 88;
	--color-orange-rgb: 254, 128, 25;
	--color-pink: var(--color-purple);
	--color-pink-rgb: var(--color-purple-rgb);
	--color-base-00: #1d2021;
	--color-base-05: #282828;
	--color-base-10: #32302f;
	--color-base-20: #3c3836;
	--color-base-25: #504945;
	--color-base-30: #665c54;
	--color-base-35: #7c6f64;
	--color-base-40: #928374;
	--color-base-50: #a89984;
	--color-base-60: #bdae93;
	--color-base-75: #b2a48c;
	--color-base-85: #c9b99a;
	--color-base-85: #d5c4a1;
	--color-base-90: #ebdbb2;
	--color-base-95: #f2e5bc;
	--color-base-100: #fbf1c7;

	--bg-hue: 0;
	--bg-sat: 17%;

	--bg2: var(--color-base-00);
	--bg3: var(--color-base-05);
	--bg4: var(--color-base-10);
	--bg5: var(--color-base-20);
	--bg6: var(--color-base-35);
	/* red */
	--color-accent: var(--color-red);
	--color-accent-hsl: 358 100% 31%;
	/* orange */
	--interactive-accent: var(--color-orange);

	/* blue */
	--secondary-accent: var(--color-blue);
	/* orange strong */
	--hover-accent: hsl(24 88% 45%);
	/* aqua */
	--link-unresolved-color: var(--color-cyan);
}
```
