### DISCUSSION TITLE
Tint Blue Color Scheme

### DISCUSSION THREAD

**Discussion by bitcrafty** [chrisgrieser/shimmering-focus#269] [Suggest your color scheme for inclusion in Shimmering Focus]
```css
.theme-dark.theme-dark {
	--bg-hue: 175;
	--bg-sat: 40%;

	--color-accent: hsl(110, 100%, 87%);
	--color-accent-hsl: hsl(110, 100%, 87%);
	--interactive-accent: #caffbf;
	--alt-heading-color: #caffbf;

	--secondary-accent: #ffe8d6;
	--hover-accent: #ffb703;
	--link-unresolved-color: #ffb703;
}
```
