### DISCUSSION TITLE
Catppuccin Mocha colors

### DISCUSSION THREAD

**Discussion by ericogilvie** [chrisgrieser/shimmering-focus#284] [Suggest your color scheme for inclusion in Shimmering Focus]
Here's a snippet based on the [Catppuccin](https://github.com/catppuccin/catppuccin)  colorscheme:
```
.theme-light.theme-light {
    --bg-hue: 222;
    --bg-sat: 16%;
    --bg-val: 218%

    --color-accent: hsl(220, 91%, 54%);
    --color-accent-hsl: 220 91% 54%;
    --interactive-accent: hsl(197, 97%, 46%);

    --alt-heading-color: hsl(232 34% 50%);
    --secondary-accent: hsl(22, 99%, 52%);
    --hover-accent: hsl(316, 73%, 69%);
    --link-unresolved-color: hsl(101 42% 51%);
}

.theme-dark.theme-dark {
    --bg-hue: 240;
    --bg-sat: 21%;
    --bg-val: 15%; 

    --color-accent: hsl(217, 92%, 76%);
    --color-accent-hsl: 217 92% 76%;
    --interactive-accent: hsl(189, 71%, 73%)

    --alt-heading-color: hsl(232 50% 70%);
    --secondary-accent: hsl(23, 92%, 75%);
    --hover-accent: hsl(316, 72%, 86%);
    --link-unresolved-color: hsl(115, 54%, 76%);
}

/* Note that `--color-accent-hsl` should have the same values as `--color-accent`, and that `--bg-hue` will override the background colors you have set in the Style Settings. */
```

**Comment by chrisgrieser** [comment]
I am considering to add some colorschemes to the theme. Would it be okay if I included this as an alternative color scheme in the theme's style settings?

**Comment by luisKisters** [comment]
Hey, firstly thanks for making this. I really like the mocha colors and the way you implemented it into my favorite theme, shimmering focus. I found a small bug that makes it kind of unusable for me. For some reason selecting text doesn't work with this enabled. Do you have any idea why this is happening?

**Reply by luisKisters** [reply]
Maybe the reason this is happening is https://github.com/tailwindlabs/tailwindcss/issues/15000. Not sure

**Comment by Nemvts** [comment]
I extended the snippet to add the color palette along with fixing the bug that @luisKisters was experiencing. I plan to continue working on this to add support for selecting a flavor and accent in Style Settings.

Here's my version of the snippet:

```css
.theme-light.theme-light {
    --rosewater: hsl(11, 59%, 67%);
    --flamingo: hsl(0, 60%, 67%);
    --pink: hsl(316, 73%, 69%);
    --mauve: hsl(266, 85%, 58%);
    --red: hsl(347, 87%, 44%);
    --maroon: hsl(355, 76%, 59%);
    --peach: hsl(22, 99%, 52%);
    --yellow: hsl(35, 77%, 49%);
    --green: hsl(109, 58%, 40%);
    --teal: hsl(183, 74%, 35%);
    --sky: hsl(197, 97%, 46%);
    --sapphire: hsl(189, 70%, 42%);
    --blue: hsl(220, 91%, 54%);
    --lavender: hsl(231, 97%, 72%);
    --text: hsl(234, 16%, 35%);
    --subtext1: hsl(233, 13%, 41%);
    --subtext0: hsl(233, 10%, 47%);
    --overlay2: hsl(232, 10%, 53%);
    --overlay1: hsl(231, 10%, 59%);
    --overlay0: hsl(228, 11%, 65%);
    --surface2: hsl(227, 12%, 71%);
    --surface1: hsl(225, 14%, 77%);
    --surface0: hsl(223, 16%, 83%);
    --base: hsl(220, 23%, 95%);
    --mantle: hsl(220, 22%, 92%);
    --crust: hsl(220, 21%, 89%);

    --bg-hue: 220;
    --bg-sat: 23%;

    --interactive-accent: var(--surface2);
    --basic-border-color: var(--surface1);

    --color-accent-hsl: 197, 97%, 46%;
    --color-accent: var(--sky);

    --alt-heading-color: var(--yellow);
    --secondary-accent: var(--green);
    --hover-accent: var(--sapphire);
    --link-unresolved-color: var(--red);

    --text-normal: var(--text);
    --icon-color: var(--text);

    /* ───────────────────────────────────────────────── */
    /** Vim Cursor
    ──────────────────────────────────────────────────── */
    --vim-cursor-outline: var(--color-accent);
    --vim-cursor-bg: var(--color-accent);

    /* ───────────────────────────────────────────────── */
    /** Text Selection (Highlight)
    ──────────────────────────────────────────────────── */
    & ::selection {
        background-color: var(--color-accent);
        color: var(--base);
    }
}

.theme-dark.theme-dark {
    --rosewater: hsl(10, 56%, 91%);
    --flamingo: hsl(0, 59%, 88%);
    --pink: hsl(316, 72%, 86%);
    --mauve: hsl(267, 84%, 81%);
    --red: hsl(343, 81%, 75%);
    --maroon: hsl(350, 65%, 77%);
    --peach: hsl(23, 92%, 75%);
    --yellow: hsl(41, 86%, 83%);
    --green: hsl(115, 54%, 76%);
    --teal: hsl(170, 57%, 73%);
    --sky: hsl(189, 71%, 73%);
    --sapphire: hsl(199, 76%, 69%);
    --blue: hsl(217, 92%, 76%);
    --lavender: hsl(232, 97%, 85%);
    --text: hsl(226, 64%, 88%);
    --subtext1: hsl(227, 35%, 80%);
    --subtext0: hsl(228, 24%, 72%);
    --overlay2: hsl(228, 17%, 64%);
    --overlay1: hsl(230, 13%, 55%);
    --overlay0: hsl(231, 11%, 47%);
    --surface2: hsl(233, 12%, 39%);
    --surface1: hsl(234, 13%, 31%);
    --surface0: hsl(237, 16%, 23%);
    --base: hsl(240, 21%, 15%);
    --mantle: hsl(240, 21%, 12%);
    --crust: hsl(240, 23%, 9%);

    --bg-hue: 240;
    --bg-sat: 21%;

    --interactive-accent: var(--surface2);

    --color-accent-hsl: 199, 76%, 69%;
    --color-accent: var(--sapphire);

    --alt-heading-color: var(--flamingo);
    --secondary-accent: var(--blue);
    --hover-accent: var(--peach);
    --link-unresolved-color: var(--red);

    --basic-border-color: var(--surface1);
    --text-normal: var(--text);
    --icon-color: var(--lavender);

    /* ───────────────────────────────────────────────── */
    /** Vim Cursor
    ──────────────────────────────────────────────────── */
    --vim-cursor-outline: var(--color-accent);
    --vim-cursor-bg: var(--color-accent);

    /* ───────────────────────────────────────────────── */
    /** Text Selection (Highlight)
    ──────────────────────────────────────────────────── */
    & ::selection {
        background-color: var(--secondary-accent);
        color: var(--crust);
    }
}
```
