### ISSUE TITLE
Feature request: block quotes made regular, not just italic

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#10]
I created a snippet, with this code block from your theme:

```
blockquote {
	margin-left: 0 !important;
	border-radius: 15px !important;
	border: 3px solid var(--text-faint) !important;
	padding-left: 1.2em !important;
	padding-right: 1.2em !important;
	padding-top: 0.8em !important;
	padding-bottom: 0.9em !important;
                                            font-style: italic; 
	margin-top: 1.5em;
	margin-bottom: 2em;
	text-align: justify;
	hyphens: auto;
	color: var(--more-contrast-muted);
}
```
However, when I change the "italic" to regular or bold, nothing happens. Any advice? I'd like the block quotes to be regular, as I have so many, the italics make it look odd, to me, though I like the frame :)
Thanks!

**Comment by chrisgrieser** [comment]
That's weird, when I change it to regular, it works fine? Did you maybe change some other css that affected this part?

```css
blockquote {
	margin-left: 0 !important;
	border-radius: 15px !important;
	border: 3px solid var(--text-faint) !important;
	padding-left: 1.2em !important;
	padding-right: 1.2em !important;
	padding-top: 0.8em !important;
	padding-bottom: 0.9em !important;
        /* here */
	font-style: regular;
	margin-top: 1.5em;
	margin-bottom: 2em;
	text-align: justify;
	hyphens: auto;
	color: var(--more-contrast-muted);
}
```
<img width="1046" alt="Screenshot 2021-09-09 12 38 38" src="https://user-images.githubusercontent.com/73286100/132671473-11a9b5d5-c024-4de5-924d-07338a772154.png">

**Comment by ReaderGuy42** [comment]
Hm, that is weird, no I don't think any other snippets would affect this, since before I was using your theme, quotes weren't italic.

**Comment by chrisgrieser** [comment]
that is weird. Still, as the change can be reversed in my case, logically, it must be some weird interaction of my theme with one of the other CSS snippets you have?

**Comment by ReaderGuy42** [comment]
I just turned off all the snippets except this one, and it was still italic?

**Comment by chrisgrieser** [comment]
Well, I can only guess, maybe it is some plugin causes the issue? You could try turning all plugins off (and also restart Obsidian) and see whether the issue persists?

**Comment by ReaderGuy42** [comment]
Sorry for the delay! I just turned off all snippets (aside from the one for the font here) and all plugins, restarted Obsidian, and it was still the same lol. It's not really that big of a deal, so I'm going to leave this for now.
Thanks for the help though!

**Comment by chrisgrieser** [comment]
> I just turned off all snippets (aside from the one for the font here)

Ah, now I got it! 💡 You were using the css above as a _snippet_, right? I thought you were modifying it in the css file of the theme. In that case, the problem is simply that your css snippet and the theme css are giving Obsidian conflicting information. 

The solution is super simple: You need to tell Obsidian to override the theme's css with your snippet's css by adding `!important` and using `unset` as value. This snippet should do it.

```css
blockquote {
	font-style: unset !important;
}
```
