### ISSUE TITLE
Feature Request: Ribbon Hover Option

### ISSUE THREAD

**Issue by JepheDelPhuego** [chrisgrieser/shimmering-focus#11]
Would be really cool to have the option to hide the ribbon unless it is hovered over. Wouldn't lose any utility while still saving space!

**Comment by chrisgrieser** [comment]
I tried to experiment with it, and got a solution that does work, but it has some repercussions, so that I think I won't include it in the theme
- to be abled to register any hover, the ribbons musst still be there, only very thin. Which looks weird, having a thin line there
- showing them on hover will move the file explorer and editor to the left, which some people will probably find annoying. flexibly changing the size of file explorer and editor mean text inside will be wrapped differently, which also comes of weird. 

However, if you want to, you can add these ass CSS snippet (while having the "show ribbons" option active), if the things above do not bother you. That should create the show-on-hover-effect that you want.

```css
body .workspace-ribbon.side-dock-ribbon.mod-left {
  flex: 0 0 5px;
}

body .workspace-ribbon.side-dock-ribbon.mod-left:hover{
	flex: 0 0 30px;
}
body .workspace-ribbon.side-dock-ribbon.mod-left:hover .side-dock-ribbon-action svg,
body .workspace-ribbon.side-dock-ribbon.mod-left:hover .workspace-ribbon-collapse-btn svg{
	display: unset;
}
.side-dock-ribbon-action svg,
.workspace-ribbon-collapse-btn svg{
	display: none;
}
```
