### ISSUE TITLE
Contribution: Tweaks for titlebar, sidebar, and ribbon workspace tabs

### ISSUE THREAD

**Issue by pryley** [chrisgrieser/shimmering-focus#139]
### Type of Contribution

Other

### Description

These are some CSS tweaks I have applied to the theme.

### Fix Window titlebar height

This is the most important tweak. This changes the title bar to the minimum titlebar height of a normal (i.e. non Electron) app, and uses flexbox to improve the navigation buttons.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/134939/162776774-23ee4ab1-c75f-4a96-9db1-9dbb26ce70da.png">

<img width="644" alt="image" src="https://user-images.githubusercontent.com/134939/162776860-ec927e4d-64ce-4105-a923-68ea6f2e4dcf.png">

```css
body.show-titlebar {
    padding-top: 28px !important;
}
body.show-titlebar .titlebar {
    height: 28px !important;
    padding-top: 0 !important;
}
body.show-titlebar .titlebar-text {
    display: block;
    font-family: system-ui;
    font-weight: 600;
    letter-spacing: 0;
    font-size: 13px;
    padding: 1px var(--cover-width) 0;
    box-sizing: border-box;
    margin: 0;
    text-overflow: hidden;
}
body.show-titlebar .titlebar-text::after {
    display: none;
}
body.show-titlebar .titlebar-button-container {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    height: 28px;
    top: 0;
}
body.show-titlebar .titlebar-button {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 2px;
}
body.show-titlebar .titlebar-button-container.mod-left svg {
    height: 20px;
    width: 20px;
}
```

### Adjust lower icons position in sidebar (subjective change)

This moves the icons in the lower part of the sidebar further down (personal preference), and uses flexbox for better positioning. 

<img width="53" alt="image" src="https://user-images.githubusercontent.com/134939/162777897-cfcda16f-3f36-4a23-8387-f303205b2a99.png">

```css
body.show-sidebar-tabs .side-dock-ribbon-action {
    display: flex;
    justify-content: center;
    margin-left: 1px;
}
body.show-sidebar-tabs .side-dock-settings {
    margin-bottom: 15px;
}
```

### Tweak style of workspace tabs in ribbons (subjective change)

This is a very subjective tweak. It makes the tab bar in the ribbons the same height as the document title, and makes the buttons more minimal.

<img width="281" alt="image" src="https://user-images.githubusercontent.com/134939/162775838-d33391c5-bf2c-45ec-b179-a5ef2c6f3a28.png">

<img width="285" alt="image" src="https://user-images.githubusercontent.com/134939/162775886-249ca4a7-c62d-43d3-953c-db2b2d8738f8.png">

```css
.workspace-tabs .workspace-tab-header-container {
    height: 30.5px;
    box-sizing: border-box;
    padding: 0;
}
body.show-header-bar .workspace-tabs .workspace-tab-header-container:hover,
body:not(.is-mobile) .workspace-tabs .workspace-tab-header-container:hover {
    border-color: var(--hover-accent-2)!important;
}
.workspace-tabs .workspace-tab-header-container .workspace-tab-header {
    height: 100%;
    margin-right: 1px;
    border: none;
    border-top: 1px solid var(--background-secondary-alt);
    box-shadow: none;
}
.workspace-tabs .workspace-tab-header-container .workspace-tab-header-inner {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 0;
    width: 40px;
    border-radius: 0;
}
.workspace-tabs .workspace-tab-header-container .workspace-tab-header-inner-icon {
    display: flex;
    align-items: center;
    justify-content: center;
}
```

### Screenshot

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/134939/162818005-a2d761ef-a97f-4f05-a551-806aaead34b3.png">
