### ISSUE TITLE
Contribution: Code block line numbers in Editor

### ISSUE THREAD

**Issue by pryley** [chrisgrieser/shimmering-focus#146]
### Type of Contribution

CSS Class(es)

### Description

This code snippet adds line numbers to code blocks in the Editor view.

**Note:** Due to the way collapsing works, The line numbers to not take collapsed code into account.

```css
.HyperMD-codeblock-begin {
    counter-reset: line-numbers;
}
.HyperMD-codeblock.cm-line:not(.HyperMD-codeblock-begin):not(.HyperMD-codeblock-end) {
    padding-left: 5em;
    position: relative;
}
.HyperMD-codeblock.cm-line:not(.HyperMD-codeblock-begin):not(.HyperMD-codeblock-end)::before {
    align-items: flex-end;
    border-right: 1px solid var(--scrollbar-thumb-bg);
    color: var(--text-faint);
    content: counter(line-numbers);
    counter-increment: line-numbers;
    display: flex;
    font-size: .8em;
    height: 100%;
    justify-content: flex-end;
    left: 0;
    padding-right: 1em;
    padding-top: 1px;
    position: absolute;
    text-align: right;
    width: 3em;
}
.HyperMD-codeblock .cm-foldPlaceholder::before {
    display: none;
}
```

### Screenshot

<img width="664" alt="image" src="https://user-images.githubusercontent.com/134939/164532788-61be0960-a525-4ae7-9173-81b760fbbf8c.png">

Collapsed code does not take the line numbering into account (because the collapsed code is removed from the page):
<img width="661" alt="image" src="https://user-images.githubusercontent.com/134939/164533477-2096689c-b37d-42e5-8939-07fc9ea2f840.png">
