### ISSUE TITLE
Contribution: Use Heading Level Indicator as the fold toggle

### ISSUE THREAD

**Issue by pryley** [chrisgrieser/shimmering-focus#147]
### Type of Contribution

CSS Class(es)

### Description

```css
body.no-heading-level-in-lp .is-live-preview .HyperMD-header .cm-fold-indicator .collapse-icon {
    align-items: flex-end;
    color: var(--text-muted);
    display: flex;
    opacity: 1 !important;
    padding-bottom: 1.5px;
}
body.no-heading-level-in-lp .is-live-preview .HyperMD-header .cm-fold-indicator.is-collapsed .collapse-icon,
.markdown-preview-view .is-collapsed :is(h1,h2,h3,h4,h5,h6) > .heading-collapse-indicator::before {
    color: var(--text-accent);
}
body.no-heading-level-in-lp .is-live-preview .HyperMD-header .cm-fold-indicator .collapse-icon:hover,
.markdown-preview-view :is(h1,h2,h3,h4,h5,h6) > .heading-collapse-indicator:hover::before {
    color: var(--hover-accent-2);
}
body.no-heading-level-in-lp .is-live-preview .HyperMD-header .cm-fold-indicator .collapse-icon::before,
.markdown-preview-view :is(h1,h2,h3,h4,h5,h6) > .heading-collapse-indicator::before {
    color: currentColor;
    font-family: var(--font-monospace);
    font-size: .8rem;
    font-style: normal;
    line-height: 1.15em;
    opacity: 1 !important;
    position: relative;
    white-space: nowrap;
}
body.no-heading-level-in-lp .is-live-preview .HyperMD-header-1 .cm-fold-indicator .collapse-icon::before,
.markdown-preview-view .el-h1 .heading-collapse-indicator::before {
    content: "H1";
}
body.no-heading-level-in-lp .is-live-preview .HyperMD-header-2 .cm-fold-indicator .collapse-icon::before,
.markdown-preview-view .el-h2 .heading-collapse-indicator::before {
    content: "H2";
}
body.no-heading-level-in-lp .is-live-preview .HyperMD-header-3 .cm-fold-indicator .collapse-icon::before,
.markdown-preview-view .el-h3 .heading-collapse-indicator::before {
    content: "H3";
}
body.no-heading-level-in-lp .is-live-preview .HyperMD-header-4 .cm-fold-indicator .collapse-icon::before,
.markdown-preview-view .el-h4 .heading-collapse-indicator::before {
    content: "H4";
}
body.no-heading-level-in-lp .is-live-preview .HyperMD-header-5 .cm-fold-indicator .collapse-icon::before,
.markdown-preview-view .el-h5 .heading-collapse-indicator::before {
    content: "H5";
}
body.no-heading-level-in-lp .is-live-preview .HyperMD-header-6 .cm-fold-indicator .collapse-icon::before,
.markdown-preview-view .el-h6 .heading-collapse-indicator::before {
    content: "H6";
}
body.no-heading-level-in-lp .is-live-preview .HyperMD-header .cm-fold-indicator .collapse-icon svg,
.markdown-preview-view :is(h1,h2,h3,h4,h5,h6) .heading-collapse-indicator svg {
    display: none;
}
body.no-heading-level-in-lp .is-live-preview .HyperMD-header .cm-foldPlaceholder {
    display: none;
}
```

### Screenshot

https://user-images.githubusercontent.com/134939/164535060-d3e353f1-816b-46ad-8338-dda2095c642a.mp4
