### ISSUE TITLE
[Bug:low priority]: Broken Ligatures

### ISSUE THREAD

**Issue by pmbauer** [chrisgrieser/shimmering-focus#176]
### Bug Description

**caveat** I'm unsure if this is a bug or not as it appears to be intentional (which is okay).

Ligatures used to work but were recently disabled.

I `git bisect`'d to [this commit](https://github.com/chrisgrieser/shimmering-focus/commit/11ce82bcb3555805e8ee5b3f7c4f97df91cbde1b#diff-2df95aa18c5c99069349aea29c452a20f8cd19a82a2bfe34532d7b72ee70f5bdR7743)

```css
/* make html comments readable by disabling ligatures in edit mode
 (only in effect when using a font different from iA Writer Quattro)  */
 .markdown-preview-view,
 .cm-s-obsidian {
 	font-variant-ligatures: none;
 }
```

Easily fixable with a snippet, so no worries.  It might be nice to enable or disable via style settings.

### Relevant Screenshot

N/A

### To Reproduce

N/A

### Obsidian Version

0.15.3

### Installer Version

0.14.15

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
oh sorry, that was simply a mistake where I forgot to change something back a while ago 🙈

it was meant to be 
```css
.cm-s-obsidian .cm-comment {
  font-variant-ligatures: none;
}
```

fixed in latest release. Thanks for pointing it out
