### ISSUE TITLE
[Bug]: Useless free space in the DB-folder plugin

### ISSUE THREAD

**Issue by flowing-abyss** [chrisgrieser/shimmering-focus#250]
### Bug Description

Incorrect display in DB-folder plugin. 

### Relevant Screenshot

Shimmering focus:
![screenshot1](https://user-images.githubusercontent.com/98622217/219879421-11e73d5e-b220-47dc-8cae-ea526aa44b04.png)

It should be :
![screenshot2](https://user-images.githubusercontent.com/98622217/219879478-157b031e-c861-4c67-bd54-fd228630f210.png)

### To Reproduce

1. Install [DB-folder](https://github.com/RafaelGB/obsidian-db-folder) plugin;
2. Create a "New database folder" in some folder;
3. Add some files with metadata to the folder;
4. Click on the file created by the DB-folder plugin.

### Obsidian Version

1.1.19

### Installer Version

1.1.19

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] When using the Obsidian Insider release, I have already checked out the [insider-branch](https://github.com/chrisgrieser/shimmering-focus#insider-release) and the issue still occurs there.
- [X] If the bug occurred after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/changelog.md) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor (CM5). (Older Obsidian versions and the Lecacy Editor are not supported by this theme anymore.)

**Comment by nilfric** [comment]
Have the same. For me it's caused by the [shimmering-focus plugin](https://github.com/chrisgrieser/shimmering-focus)

Workaround:
```css
/*
 * Shimmering focus plugin causes unecessary top padding in db folder plugin tables
 * https://github.com/chrisgrieser/shimmering-focus/issues/250
 */
.mod-root .markdown-preview-view:not(.kanban-plugin__markdown-preview-view), .mod-root .markdown-source-view.mod-cm6 .cm-scroller {
    padding-top: 0px;
}
```
