### ISSUE TITLE
Change font color in dark mode for highlight alt 2

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#37]
I have several snippets that change around the highlight colors, the normal is ==yellow==, alt 1 is **==cyan==**, alt 2 is *==red==*. 

I've noticed that in dark mode the font color for alt 2 is white along with that of all the rest of the words. 
Due to the redish color that is quite difficult to read, is there a way to change the font for the highlight alt 2 to stay black?

Thanks!!

**Comment by chrisgrieser** [comment]
I think something like this will do :)

```css
span.cm-em.cm-highlight {
	font-style: initial;
	background-color: #FFAA9750;
	color: #222;
}
body > .app-container div.markdown-preview-view em > mark {
	font-style: initial !important;
	background-color: #FFAA9750;
	color: #222;
}
```
