### ISSUE TITLE
Feature Request: An option for the horizontal lines for the outline

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#65]
**Feature Requested**
I love the horizontal lines for the outline that you set in previous versions of this theme since they helped me navigate between headings very easily. I wonder if you can put an option in the Style Setting plugin for these horizontal lines. I would greatly appreciate it if you don't mind considering my request.

**Checklist**
- [X] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
I am still unsure what kind of styling I want to to with the outline plugin, so that part might change.

However, you can simply add a css snippet with this to disable the alternating row-colors and enable the horizontal lines in the outline view until I settle on something

```css
body .app-container .outline .tree-item:nth-child(even) {
	background-color: transparent;
}

.outline .tree-item-self {
	border-bottom: var(--thin-border);
}
```
