### ISSUE TITLE
Question: How to highlight <-- comment --> with another color?

### ISSUE THREAD

**Issue by Liong1976** [chrisgrieser/shimmering-focus#90]
### Feature Requested

I was wondering if there is CSS that can change the color of <--comment--> to another color instead of grey (the default). I need the color more stand out so that I won't forget to add something according to the comment.

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
yep, you can via this css (just ignore the weird css on this one, it's to avoid `!importants`)

```css
body .cm-comment.cm-comment.cm-comment.cm-comment.cm-comment {
	color: yourcolor;
}
```
